
ENTITY_NAMESPACE := hetero.decoder.mpeg.rvc
ENTITY_NETWORK ?= Top_mpeg4_part2_SP_decoder
ENTITY := $(ENTITY_NAMESPACE).$(ENTITY_NETWORK)
CAL_SOURCE_PATH := $(shell pwd)

include ../common.mk
include ../rules.mk