

$(ENTITY_NETWORK)_HLS_SYSTEMC: $(CAL_DEPS)
	$(SB_BIN) vivado-hls $(SYSTEMC_SETTIGNS) $(COMMON_SETTINGS) $(HLS_SETTINGS) $(PATH_SETTINGS) $(ENTITY)

$(ENTITY_NETWORK)_MULTICORE_SYSTEMC: $(CAL_DEPS)
	$(SB_BIN) multicore $(SYSTEMC_SETTIGNS) $(COMMON_SETTINGS)  $(MULTICORE_SETTIGS) $(PATH_SETTINGS) $(ENTITY)

$(ENTITY_NETWORK)_SYSTEMC: $(ENTITY_NETWORK)_MULTICORE_SYSTEMC $(ENTITY_NETWORK)_HLS_SYSTEMC
	cd $(TARGET_PATH); \
	mkdir -p build; \
	cd build; \
	$(CMAKE) .. -DCMAKE_BUILD_TYPE=Release -DHLS_CLOCK_PERIOD=$(HLS_CLOCK_PERIOD); \
	make $(ENTITY_NETWORK) -j

$(ENTITY_NETWORK)_HLS: $(CAL_DEPS)
	$(SB_BIN) vivado-hls $(COMMON_SETTINGS) $(HLS_SETTINGS) $(PATH_SETTINGS) $(ENTITY)

$(ENTITY_NETWORK)_MULTICORE: $(CAL_DEPS)
	$(SB_BIN) multicore $(COMMON_SETTINGS) $(MULTICORE_SETTIGS) $(PATH_SETTINGS) $(ENTITY)

$(ENTITY_NETWORK):$(ENTITY_NETWORK)_HLS $(ENTITY_NETWORK)_MULTICORE 
	

clean:
	rm -r $(TARGET_PATH)