
ENTITY_NAMESPACE := hetero.decoder.mpeg.xilinx
ENTITY_NETWORK := XilinxNetwork
ENTITY := $(ENTITY_NAMESPACE).$(ENTITY_NETWORK)

CAL_SOURCE_PATH := $(shell pwd)

include ../common.mk

include ../rules.mk

# ENTITY_NETWORK := XilinxTester
# ENTITY := $(ENTITY_NAMESPACE).$(ENTITY_NETWORK)


# include ../rules.mk